spring.cloud.stream.bindings.singleOutput.contentType: application/json
#spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000


#binders configuration:
spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
#  brokers: kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092


#bindings configuration:

spring.cloud.stream.bindings.topic1:
  destination: test
  binder: kafka

spring.cloud.stream.bindings.topic2:
  destination: cattolica
  binder: kafka

spring.cloud.stream.bindings.topic3:
  destination: managedAlarms
  group:
  binder: kafka

